#!/bin/sh
confirm "Run lint checks?" || exit 0

# Disable concurent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.." && npx --no lint-staged --concurrent false

confirm "Run build?" || exit 0

yarn build