#!/bin/sh

# Define confirm function
confirm() {
    # Default to Yes if no answer is given
    read -r "$1 [Y/n] " response
    case "$response" in
        [nN][oO]|[nN])
            return 1
            ;;
        *)
            return 0
            ;;
    esac
}

confirm "Run lint checks?" || exit 0

# Disable concurrent to run `check-types` after ESLint in lint-staged
cd "$(dirname "$0")/.." && bunx lint-staged --concurrent false

confirm "Run tests?" || exit 0

bun run test

confirm "Run build?" || exit 0

bun run build
